### PR TITLE
Update typo on DPSMate_DataBuilder.lua

### PR DESCRIPTION
**Pull request by nemesis2100**
line 1395, "DSPMate" to "DPSMate"

### CODE REVIEW

**Comment by nemesis2100** [comment]
Anyone? Anyone? Bueller?

**Comment by herkan** [comment]
Bueller?

**Comment by nemesis2100** [comment]
Been about a month now.  Anyone feel like finalizing this?
@Geigerkind

**Comment by Geigerkind** [comment]
Sorry about it, I rarely look into this project anymore.
Thanks!

**Pull request merged**
