### PR TITLE
[fix] HoT parser indexing

### LINKED ISSUE #213: attempt to perform arithmetic on nil value (reopen)
Getting this error again with latest release (b19 - 2 hours ago).  Full CLEAN install after removing all DPSm* files from WoW dir. 

Occurs when Voidwalker is healed with Consume Shadows.
image

### LINKED ISSUE #236: Error:  attempt to perform arithmetic on local `amount' (a nil value)
Error:  attempt to perform arithmetic on local `amount' (a nil value)
AddOn: DPSMate
File: DPSMate_ParserENUS.lua
Line: 1777
Count: 6

Error occured when I bandaged myself after taking falldmg.

### PR DESCRIPTION
**Pull request by MichalKalinec**
Resolves #236
Resolves #213

### CODE REVIEW

**Comment by armoha** [comment]
Isn't this just reverting #232 ? Merging this PR may reopen other issues like #228 and #231 .

**Comment by MichalKalinec** [comment]
Good point, I didn't test it with pets, but seems like you're right. I guess this issue needs more complex modification to distinct between players and pets? Unfortunately I don't really know Lua and WoW addons well enough to make this work for both cases...

**Comment by trumpetx** [comment]
Here's what I did to make the errors go away: 

`if amount==nil then amount=0 end` before `amount` is used.  I don't know if it's parsing correctly, but it's close enough for me.

**Comment by sipertruk** [comment]
#232 only fix it for a pet name of length 5
the variable k should be set to the start of  the heal value when a pet is found (that's when " gains " is found)
I didn't test it
~~~~diff
function DPSMate.Parser:SpellPeriodicSelfBuff(msg)
-	local i,j,k = 0,0,12
+	local i,j,k = 0,0,10
	local nextword, choice;
	nextword, choice, k = GetNextWord(msg, k, SPSBChoices, false)
	if choice == -1 then
		local debug = DPSMate.Debug and DPSMate.Debug:Store("18: Event not parsed yet => "..msg) or DPSMate:SendMessage("18: Event not parsed yet, inform Shino! => "..msg)
		return
	end
	
	if choice <= 2 then
		local source = Player;
		local i,j = strfind(nextword, " gains ", 1, true)
		if i and j then
			source = strsub(nextword, 1, i-1);
			nextword = strsub(nextword, j+1);
+			k = i + 7
		end
~~~~

**Comment by laytya** [comment]
It will not fix it. Wrong logic....

**Comment by tdymel** [comment]
Closing it for now.

**Pull request closed without merging**
