### PR TITLE
Fix init error with combatlog extender, use traffic shaping to alleviate slowdowns

### PR DESCRIPTION
**Pull request by Road-block**
Embed and use ChatThrottleLib to manage both addon and chat communication.   
_(same library is hard-embedded in AceComm-2.0, but the other facilities of AceComm-2.0 are not needed here)_

Also re-adds the combatlog extension to 200y at an appropriate event to avoid initialization error.

### CODE REVIEW

**Comment by ohganot** [comment]
Does this by any chance solve the lag issues caused by syncing?

**Comment by Road-block** [comment]
That's the idea.

**Comment by Razorwynd** [comment]
I can confirm that this really does help!

**Comment by Geigerkind** [comment]
Thank you!

**Pull request merged**
